language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install pip
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install . -r requirements.txt # install package + test dependencies

script:
  - pytest # run tests
after_success:
  # - pytest
  - pytest --cov=./ --cov-report=xml
  - codecov # submit coverage
