language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install ".[test]" . # install package + test dependencies
  - pytest --cov=./ --cov-report=xml
script: pytest # run tests
after_success:
  - codecov # submit coverage

